import { useMemo, useState } from 'react'
import { diagnosticModes, type DiagnosticEvent, type DiagnosticVersion } from './diagnosticModes'
import { getQuestion, maturityOptions } from './questionBank'
import type { BusinessFact, V2View } from './v2data'
import { useDeskMotion } from './useDeskMotion'

const nav:{id:V2View;label:string;icon:string}[]=[
  {id:'cockpit',label:'诊断驾驶舱',icon:'⌂'},{id:'facts',label:'信息台账',icon:'≡'},
  {id:'questionnaire',label:'关联补充',icon:'□'},{id:'graph',label:'事件关系',icon:'⌘'},
  {id:'routes',label:'咨询路由',icon:'↗'},{id:'execution',label:'执行追踪',icon:'✓'},
]

function VersionSwitch({version}:{version:DiagnosticVersion}){
  return <div className="v2-version-switch"><a className={version==='2.1'?'active':''} href="?v=2.1">V2.1 专项版</a><a className={version==='2.2'?'active':''} href="?v=2.2">V2.2 CEO版</a><a href="?v=3">V3 联合版</a></div>
}

function Landing({version,onStart}:{version:DiagnosticVersion;onStart:(profile:{company:string;industry:string;size:string;event:DiagnosticEvent})=>void}){
  const mode=diagnosticModes[version]
  const [company,setCompany]=useState('澄明科技有限公司');const [industry,setIndustry]=useState('企业服务 / SaaS');const [size,setSize]=useState('51—100人');const [eventId,setEventId]=useState(mode.events[0].id)
  const event=mode.events.find(item=>item.id===eventId)!
  useDeskMotion(`landing-${version}`)
  return <main className={`v2-landing mode-${version.replace('.','-')}`}>
    <header className="v2-landing__nav"><div className="v2-brand"><span>O</span><b>OrgHealth</b><em>V{version}</em></div><VersionSwitch version={version}/></header>
    <section className="v2-hero"><p>{mode.kicker}</p><h1>{mode.title}</h1><span>{mode.summary}<br/>适用对象：{mode.audience}</span></section>
    <section className="v2-create"><div className="v2-profile"><div className="v2-section-label"><b>01</b><span>企业信息</span></div><label>企业名称<input value={company} onChange={x=>setCompany(x.target.value)}/></label><div className="v2-field-row"><label>所属行业<select value={industry} onChange={x=>setIndustry(x.target.value)}><option>企业服务 / SaaS</option><option>制造业</option><option>消费品</option><option>专业服务</option><option>零售与电商</option></select></label><label>企业规模<select value={size} onChange={x=>setSize(x.target.value)}><option>20人以下</option><option>21—50人</option><option>51—100人</option><option>101—300人</option><option>300人以上</option></select></label></div></div>
      <div className="v2-event-pick"><div className="v2-section-label"><b>02</b><span>目前实际发生了什么？</span><small>只选择可观察事件，不选择系统预设的根因</small></div><div className="v2-event-grid">{mode.events.map(item=><button key={item.id} className={eventId===item.id?'active':''} onClick={()=>setEventId(item.id)}><i>{item.icon}</i><span><strong>{item.name}</strong><small>{item.description}</small></span><b>{eventId===item.id?'✓':'+'}</b></button>)}</div></div></section>
    <section className="v2-startbar"><div><span>当前事件 · {event.id}</span><strong>{event.name}</strong><small>下一步只回答与该事件映射的 {event.core.length} 个核心题项</small></div><button disabled={!company.trim()} onClick={()=>onStart({company,industry,size,event})}>进入核心诊断 <b>→</b></button></section>
  </main>
}

function Intake({version,profile,onBack,onComplete}:{version:DiagnosticVersion;profile:{company:string;industry:string;size:string;event:DiagnosticEvent};onBack:()=>void;onComplete:(answers:Record<number,string>)=>void}){
  const [answers,setAnswers]=useState<Record<number,string>>({});const questions=profile.event.core.map(getQuestion);const complete=questions.filter(q=>answers[q.id]).length
  useDeskMotion(`intake-${version}-${profile.event.id}`)
  return <main className="v2-intake"><header><div className="v2-brand"><span>O</span><b>OrgHealth</b><em>V{version}</em></div><button onClick={onBack}>← 返回事件选择</button></header><section className="v2-intake-head"><p>CORE MAPPING · STEP 1</p><h1>“{profile.event.name}”的核心映射题</h1><span>{profile.company} · {profile.industry} · {profile.size}</span><div><i style={{width:`${complete/questions.length*100}%`}}/></div><small>完成后只显示初步咨询方向，不显示置信度，也不会直接宣布根因。</small></section><section className="v2-intake-form">{questions.map(q=><label key={q.id}><b>Q{q.id}</b><span><strong>{q.title}</strong><small>{q.prompt}</small></span><select value={answers[q.id]??''} onChange={x=>setAnswers({...answers,[q.id]:x.target.value})}><option value="">请选择</option>{maturityOptions.map(o=><option key={o}>{o}</option>)}</select></label>)}</section><section className="v2-intake-foot"><div><strong>第一轮只做方向分流</strong><span>{profile.event.rationale}</span></div><button disabled={complete<questions.length} onClick={()=>onComplete(answers)}>{complete<questions.length?`还需完成 ${questions.length-complete} 项`:'查看初步咨询方向 →'}</button></section></main>
}

function Graph({event,selected}:{event:DiagnosticEvent;selected:string[]}){
  return <div className="v2-relation-map"><article className="root"><small>已观察事件</small><strong>{event.name}</strong><span>{event.id}</span></article><div className="relation-line"/><section>{event.branches.map(branch=><article key={branch.id} className={selected.includes(branch.id)?'confirmed':''}><small>{selected.includes(branch.id)?'已确认关联':'待确认关联'}</small><strong>{branch.label}</strong><span>{branch.description}</span></article>)}</section></div>
}

function Workspace({version,profile,initialAnswers,onExit}:{version:DiagnosticVersion;profile:{company:string;industry:string;size:string;event:DiagnosticEvent};initialAnswers:Record<number,string>;onExit:()=>void}){
  const {event}=profile;const [view,setView]=useState<V2View>('cockpit');const [answers,setAnswers]=useState(initialAnswers);const [selected,setSelected]=useState<string[]>([]);const [accepted,setAccepted]=useState<number|null>(null)
  const relatedIds=useMemo(()=>Array.from(new Set(event.branches.filter(x=>selected.includes(x.id)).flatMap(x=>x.questionIds))),[event,selected])
  const relatedAnswered=relatedIds.filter(id=>answers[id]).length
  const confidence=relatedAnswered===0?null:Math.min(93,55+Math.round(relatedAnswered/Math.max(1,relatedIds.length)*33)+Math.min(5,selected.length*2))
  useDeskMotion(`workspace-${view}-${selected.join('-')}-${relatedAnswered}`)
  const facts:BusinessFact[]=Object.entries(answers).map(([id,value],index)=>{const q=getQuestion(Number(id));return{id:index+1,type:'经营指标',name:`Q${id} ${q.title}`,value,comparison:event.core.includes(Number(id))?'核心映射题 · 企业自述':'关联补充题 · 企业自述',period:'当前周期',status:'企业自述'}})
  const toggle=(id:string)=>setSelected(old=>old.includes(id)?old.filter(x=>x!==id):[...old,id])
  const answer=(id:number,value:string)=>setAnswers(old=>({...old,[id]:value}))
  return <div className={`v2-shell mode-${version.replace('.','-')}`}><aside className="v2-sidebar"><button className="v2-brand" onClick={onExit}><span>O</span><b>OrgHealth</b><em>V{version}</em></button><div className="v2-company"><small>当前企业</small><strong>{profile.company}</strong><span>{profile.industry} · {profile.size}</span></div><nav>{nav.map(item=><button key={item.id} className={view===item.id?'active':''} onClick={()=>setView(item.id)}><i>{item.icon}</i>{item.label}{item.id==='questionnaire'&&<b>{relatedAnswered}/{relatedIds.length}</b>}</button>)}</nav><div className="v2-side-event"><small>{event.id} · 当前事件</small><strong>{event.name}</strong><span>已确认 {selected.length}/{event.branches.length} 个关联事件</span></div><VersionSwitch version={version}/></aside>
    <main className="v2-main"><header className="v2-top"><div><p>{diagnosticModes[version].name}</p><h1>{nav.find(x=>x.id===view)?.label}</h1></div><div><span>● Skill映射演示</span><i>顾</i></div></header><div className="v2-notice"><b>事件不是结论</b><span>核心题只生成初步方向；确认关联事件并补充题项后，才显示推荐置信度。</span></div>
      {view==='cockpit'&&<><section className="v2-event-hero"><div><p>{event.id} · OBSERVED EVENT</p><h2>{event.name}</h2><span>{event.description}</span></div><div className="v2-readiness"><span>初步推荐方向</span><strong className="v2-direction">{event.direction}</strong><small>{confidence===null?'初步阶段不显示置信度':`推荐置信度 ${confidence}%`}</small></div></section><section className="v2-kpis"><article><span>核心题</span><strong>{event.core.length}</strong><small>来自原56题映射</small></article><article><span>候选关联事件</span><strong>{event.branches.length}</strong><small>需要客户确认</small></article><article><span>已确认关联</span><strong>{selected.length}</strong><small>确认后才展开补充题</small></article><article><span>推荐置信度</span><strong>{confidence===null?'—':`${confidence}%`}</strong><small>{confidence===null?'补充信息后生成':'不是健康度得分'}</small></article></section><section className="v2-panel v2-branch-panel"><div className="v2-panel-head"><div><p>RELATED EVENTS</p><h2>这些情况是否也在发生？</h2><span>系统根据当前事件提出候选关联，不直接认定它们是根因。</span></div></div><div className="v2-branch-grid">{event.branches.map(branch=><button key={branch.id} className={selected.includes(branch.id)?'active':''} onClick={()=>toggle(branch.id)}><i>{selected.includes(branch.id)?'✓':'+'}</i><span><strong>{branch.label}</strong><small>{branch.description}</small></span><b>{branch.questionIds.length} 个补充项</b></button>)}</div>{selected.length>0&&<button className="v2-primary" onClick={()=>setView('questionnaire')}>填写已确认事件的补充题 →</button>}</section></>}
      {view==='facts'&&<section className="v2-page"><div className="v2-page-title"><div><p>ANSWER LEDGER</p><h2>输入信息台账</h2><span>每项都保留题号和来源，不把企业自述伪装成核验结论。</span></div></div><div className="v2-fact-table"><div className="head"><span>题项</span><span>回答</span><span>信息阶段</span><span>期间</span><span>状态</span></div>{facts.map(f=><div className="row" key={f.id}><div><i>Q</i><span><strong>{f.name}</strong><small>{f.type}</small></span></div><b>{f.value}</b><span>{f.comparison}</span><span>{f.period}</span><em className="fact-tag fact-tag--企业自述">企业自述</em></div>)}</div></section>}
      {view==='questionnaire'&&<section className="v2-page"><div className="v2-page-title"><div><p>CONFIRMED BRANCHES</p><h2>关联事件补充信息</h2><span>{selected.length===0?'请先确认正在发生的关联事件。':'只展示已确认关联事件对应的题项。'}</span></div>{relatedIds.length>0&&<span className="v2-ready">{relatedAnswered}/{relatedIds.length}</span>}</div>{selected.length===0?<div className="v2-empty"><i>□</i><h3>尚未确认关联事件</h3><p>系统不会一次性弹出所有问卷。请先返回驾驶舱确认哪些关联情况确实发生。</p><button onClick={()=>setView('cockpit')}>确认关联事件</button></div>:<><div className="v2-branch-tags">{event.branches.filter(x=>selected.includes(x.id)).map(x=><button key={x.id} onClick={()=>toggle(x.id)}>✓ {x.label} ×</button>)}</div><div className="v2-supplement-list">{relatedIds.map(id=>{const q=getQuestion(id);return <label key={id}><b>Q{id}</b><span><strong>{q.title}</strong><small>{q.prompt}</small></span><select value={answers[id]??''} onChange={x=>answer(id,x.target.value)}><option value="">暂不填写</option>{maturityOptions.map(o=><option key={o}>{o}</option>)}</select></label>})}</div>{confidence!==null&&<div className="v2-confidence-result"><div><span>方向推荐置信度</span><strong>{confidence}%</strong></div><p>表示“{event.direction}”作为下一步咨询方向的可靠程度；由已确认关联事件、题项覆盖和答案信息共同形成，不代表问题严重程度。</p><button onClick={()=>setView('routes')}>查看咨询路线 →</button></div>}</>}</section>}
      {view==='graph'&&<section className="v2-page"><div className="v2-page-title"><div><p>EVENT RELATION</p><h2>事件与题库映射</h2><span>实线起点是客户选择的事件，分支只有经客户确认后才进入补充题。</span></div></div><Graph event={event} selected={selected}/></section>}
      {view==='routes'&&<section className="v2-page"><div className="v2-page-title"><div><p>CONSULTING ROUTER</p><h2>咨询方向推荐</h2><span>{confidence===null?'当前只有初步方向，尚不能生成带置信度的路线排序。':'基于已确认关联事件和补充题生成。'}</span></div>{confidence!==null&&<span className="v2-ready">推荐置信度 {confidence}%</span>}</div>{confidence===null?<div className="v2-empty"><i>↗</i><h3>初步方向：{event.direction}</h3><p>先确认关联事件并至少补充一项信息，系统才显示路线置信度。</p><button onClick={()=>setView(selected.length?'questionnaire':'cockpit')}>{selected.length?'补充信息':'确认关联事件'}</button></div>:<div className="v2-route-list">{event.routes.map((name,index)=><article key={name} className={accepted===index?'accepted':''}><div className="v2-rank">0{index+1}</div><div className="v2-route-body"><div><span>{index===0?'优先建议':index===1?'备选方向':'前置能力'}</span><h3>{name}</h3><small>由 {selected.length} 个已确认关联事件支持</small></div><p>{index===0?event.rationale:`作为“${event.direction}”的${index===1?'相邻':'支撑'}咨询模块进一步验证。`}</p><div className="v2-triggers">{event.branches.filter(x=>selected.includes(x.id)).map(x=><span key={x.id}>✓ {x.label}</span>)}</div></div><div className="v2-route-score"><strong>{Math.max(40,confidence-index*13)}<small>%</small></strong><span>推荐置信度</span><button onClick={()=>setAccepted(index)}>{accepted===index?'已选择':'选择路线'}</button></div></article>)}</div>}</section>}
      {view==='execution'&&<section className="v2-page"><div className="v2-page-title"><div><p>EXECUTION</p><h2>执行追踪</h2><span>只有选择咨询路线后才建立改善项目。</span></div></div>{accepted===null?<div className="v2-empty"><i>✓</i><h3>尚未选择咨询路线</h3><button onClick={()=>setView('routes')}>前往咨询路由</button></div>:<div className="v2-execution-card"><span>已选择路线</span><h3>{event.routes[accepted]}</h3><p>下一步由顾问确认范围、目标指标和项目周期。</p><button>创建改善项目 →</button></div>}</section>}
    </main></div>
}

export default function V2App({version}:{version:DiagnosticVersion}){
  const [profile,setProfile]=useState<{company:string;industry:string;size:string;event:DiagnosticEvent}|null>(null);const [answers,setAnswers]=useState<Record<number,string>|null>(null)
  if(!profile)return <Landing version={version} onStart={setProfile}/>
  if(!answers)return <Intake version={version} profile={profile} onBack={()=>setProfile(null)} onComplete={setAnswers}/>
  return <Workspace version={version} profile={profile} initialAnswers={answers} onExit={()=>{setProfile(null);setAnswers(null)}}/>
}
